repos:
-   repo: https://github.com/jleclanche/tan
    rev: 22.8.0
    hooks:
    -   id: black
        args: [-l 100]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
